config/routes.rb
MestOMatic::Application.routes.draw do
  root :to => "welcome#index"
  
  resource :sessions
  resources :users do
    collection do
      get 'unassigned_roles'
      put 'assign_roles'
    end
  end
  resources :projects do
    resources :deliverables do
      member do
        get 'download'
        get 'upload'
        post 'process_upload'
      end
      resources :reviews do
        collection do
          post 'mass_create'
        end
      end
      resources :submissions
    end
    resources :teams
  end
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  match '/testlogin/:id' => 'sessions#testlogin'

end

app/models/deliverable.rb
# == Schema Information
# Schema version: 20110616104908
#
# Table name: deliverables
#
#  id             :integer         not null, primary key
#  title          :string(255)
#  description    :string(255)
#  start_date     :datetime
#  end_date       :datetime
#  project_id     :integer
#  created_at     :datetime
#  updated_at     :datetime
#  author_id      :integer
#  graded         :boolean
#  last_graded_at :date
#
class Deliverable < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  
  has_many :solutions
  has_many :submissions, :through => :solutions

  accepts_nested_attributes_for :solutions

  validates :title, :presence => true
  validates_uniqueness_of :title, :scope => :project_id, :case_sensitive => false
  validates :project, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :author, :presence => true
  validate :start_date_must_be_before_end_date
  
  after_create do |d|
    eits.each do |eit| 
      s = Solution.create(:deliverable => d, :user => eit)
      Submission.create(:solution => s)
    end
  end   
  
  def eits
    project.class_of.eits
  end

  def eits_submitted
    solutions.select{|sol| sol.submissions.select{|sub| sub.is_a?(FileSubmission)}.size > 0}.collect{|sol| sol.user}
  end

  def safe_title
    title.gsub(/\s/, "_").camelize.gsub(/[^a-zA-Z0-9]/, "")
  end

  def start_date_must_be_before_end_date
    errors.add(:end_date, 'must be after start date') if start_date and end_date and start_date >= end_date
  end

  def invisible?
    start_date >= Time.now
  end

  def visible?(user)
    return true if user.staff?
    not invisible?
  end
  
  def current?
    end_date > DateTime.now
  end
  
  def ended?
    not current?
  end
  
  def not_graded_yet?
    not graded?
  end

  def reviews_missing? 
    latest_version.select{|sub| sub.review.nil?}.size > 0
  end

  def closed?
    graded? and end_date < Time.now - 1.months
  end
  
  def newest_submissions_all_graded?
    reviews = solutions.collect{|s| s.submissions.sort{|a,b| a.created_at<=> b.created_at}.last.review}
    return (not reviews.include?(nil))
  end

  def not_closed_yet?
    not closed?
  end

  def submissions_for(by_user)
    user_solution = solutions.select{|sol| sol.user.eql?(by_user)}.first
    if user_solution
      user_solution.submissions.select{|sub| sub.is_a?(FileSubmission)} 
    else
      [] #TODO: Can I remove this branch?
    end
  end
  
  def review_for(by_user)
    result = nil
    user_solution = solutions.select{|sol| sol.user.eql?(by_user)}.first
    reviewed_solution = user_solution.submissions.select{|s| s.review}.sort{|a,b| a.updated_at <=> b.updated_at}.first
    result = reviewed_solution.review if reviewed_solution
    return result
  end

  def not_submitted?(by_user)
    submissions_for(by_user).empty?
  end
  
  def submitted?(by_user)
    submissions_for(by_user).size > 0
  end

  def latest_submission(by_user)
    submissions_for(by_user).sort{|a,b| a.created_at <=> b.created_at}.first
  end
  
  def submitted_on_time?(by_user)
    latest_submission(by_user).created_at <= end_date
  end
  
  def submitted_too_late?(by_user)
    submitted?(by_user) and not submitted_on_time?(by_user)
  end

  def versions 
    current_submissions = solutions.map{|sol| sol.submissions.first}
    versions = {0 => current_submissions}
    submissions.select{|sub| sub.is_a?(FileSubmission)}.sort{|a,b| a.created_at <=> b.created_at}.each_with_index do |sub, i|
      current_submissions = Array.new(current_submissions).reject{|s| sub.solution == s.solution}
      current_submissions << sub
      versions[i+1] = current_submissions
    end
    return versions
  end

  def download_latest_version
    download_version(latest_version_nr)
  end
  
  def latest_version
    versions[latest_version_nr]
  end

  def latest_version_nr
    versions.keys.max
  end

  def process_corrections_archive(file)
    filename = file.is_a?(String) ? file : file.path
    tmpdir = File.join(Dir.tmpdir, "#{File.basename(filename)}-unzipped")
    unzipped_dir = MyZip.unzip_file(file,tmpdir)
    unzipped_files = Dir.entries(unzipped_dir).reject{|d| %w[. ..].include?d}
    if unzipped_files.size == 1 and File.directory?(File.join(unzipped_dir, unzipped_files.first)) then
      eit_root = File.join(unzipped_dir, unzipped_files.first)
      eit_folders = Dir.entries(eit_root).reject{|d| %w[. ..].include?d}
      if has_a_folder_and_a_review_for_each_student(eit_folders, eits_submitted) then
        extract_eits_and_reviews(eit_folders).each_pair do |eit,review|
          zipfile = File.join(tmpdir, "Review_of_#{project.safe_title}_#{safe_title}_ver#{review.submission.version}.zip")
          folder = File.join(eit_root, "#{eit.identifier_name}_#{review.submission.version}")
          MyZip.zip_file(folder, zipfile)
          review.archive = File.open(zipfile, "rb") if File.exists?(zipfile)
          review.save #need to save to add the zipfile
          #TODO: Delete temp files
        end
        return true
      end
    end
    false
  end

  def has_a_folder_and_a_review_for_each_student(folders, list_of_students)
    extract_eits_and_reviews(folders).keys.collect{|e| e.identifier_name}.sort == list_of_students.collect{|e| e.identifier_name}.sort
  end

  def extract_eits_and_reviews(folders)
    result = {}
    folders.each do |folder|
      if matchdata = folder.match(/(.*)_(\d+)$/) then
        eit = eits_submitted.select{|e| e.identifier_name == matchdata[1]}.first
        version = matchdata[2].to_i
        sol = Solution.find_or_create(:user => eit, :deliverable => self) if eit
        if sol and sol.submissions.size-1>=version then
          review = sol.submissions[version].review 
          result[eit] = review if eit and review
        end
      end
    end
    return result
  end

  private
    def version_unzipped_path(nr)
      File.join(Rails.root, "public/system/unzipped/deliverable_versions", nr.to_s)
    end

    def download_version(nr)
      zip_file_name = "#{id}_#{project.safe_title}_#{safe_title}_ver#{nr}" 
      zip_file_path = File.join(Rails.root, "public/system/deliverables/#{zip_file_name}.zip")
      unless File.exists?(zip_file_path) then
        FileUtils.mkdir_p(File.dirname(zip_file_path))
        temp_folder = version_unzipped_path(nr)
        FileUtils.rm_r(temp_folder) if File.exists?(temp_folder) # Start with a clean slate
        FileUtils.mkdir_p(temp_folder)
        #Copy everything into temp_folder
        versions[nr].each do |submission| 
          user_dest = File.join(temp_folder, "#{submission.user.identifier_name}_#{submission.version}") 
          FileUtils.cp_r(submission.unzipped_path, user_dest) if submission.is_a? Filesubmission and not RAILS_ENV == 'test' #TODO: Find a way to test uploads!
        end 
        #Create zipfile out of temp_folder
        MyZip.zip_file(temp_folder, zip_file_path)
      end
      #send_file t.path, :type => 'application/zip', :disposition => 'attachment', :filename => "some-brilliant-file-name.zip"
      zip_file_path
    end
end

app/controllers/deliverables_controller.rb
class DeliverablesController < ApplicationController
  before_filter :load_project
  before_filter :ensure_signed_in
  before_filter :require_staff
  
  def new
    @deliverable = Deliverable.new
  end

  def create
    @deliverable = Deliverable.new(params[:deliverable])
    @deliverable.author_id = current_user.id
    @project.deliverables << @deliverable
    if params[:commit].eql?("cancel") or @deliverable.save
      #@project.eits.each do |eit|
      #  s = Solution.new(:user => eit)
      #  @deliverable.solutions << s
      #end
      flash[:notice] = "Successfully created the deliverable #{@deliverable.title}" if @deliverable.save
      redirect_to project_path(@project) 
    else
      @project.deliverables.delete(@deliverable)
      render :action => "new"
    end
  end

  def download
    deliverable = Deliverable.find(params[:id])
    VersionDownload.create(:deliverable => deliverable, :version_nr => deliverable.latest_version_nr, :downloader => current_user)
    send_file deliverable.download_latest_version
    #redirect_to project_path(@project)
  end

  def upload
    @deliverable = Deliverable.find(params[:id])
  end

  def process_upload
    @deliverable = Deliverable.find(params[:id])
    if @deliverable.process_corrections_archive(params[:archive].tempfile) then
      flash[:notice] = "Successfully distributed your corrections to the students"
      redirect_to project_path(@project)
    else
      flash[:error] = "The archive that you uploaded did not contain a folder for each student that submitted or had additional folders"
      render :action => "upload" 
    end
  end

  private
    def load_project
      @project = Project.find(params[:project_id])
    end
end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
  def time_span_to_due_date_in_words(deliverable)
    distance = distance_of_time_in_words_to_now(deliverable.end_date)
    if deliverable.current? then
      "due in #{distance}"
    else
      "was due #{distance} ago"
    end
  end
  
  def status_icon(deliverable, user)
    if user.eit? then
      if deliverable.current? then
        if deliverable.submitted?(user) then
          haml_tag :img, :src => "/icons/submitted.png", :alt => "You submitted a version."
        else
          haml_tag :img, :src => "/icons/notsubmitted.png", :alt => "You did not submit a version yet."
        end
      elsif deliverable.ended? and deliverable.not_graded_yet? then
        if deliverable.submitted?(user) then
          haml_tag :img, :src => "/icons/clock.png", :alt => "Grading in progress."
          haml_tag :img, :src => "/icons/submitted.png", :alt => "You submitted a version." if deliverable.submitted_on_time?(user)
          haml_tag :img, :src => "/icons/submitted-late.png", :alt => "You submitted a version." if deliverable.submitted_too_late?(user)
        else
          haml_tag :img, :src => "/icons/notsubmitted-late.png", :alt => "You did not submit a version yet."
        end
      elsif deliverable.graded? and deliverable.not_closed_yet?
        if deliverable.review_for(user)
          haml_tag :img, :src => "/icons/exclamation.png", :alt => "You submitted too late."
          haml_tag :span, "#{deliverable.review_for(user).percentage}%" 
        else
          haml_tag :img, :src => "/icons/notsubmitted-late.png", :alt => "You did not submit a version yet."
        end
      elsif deliverable.closed?
        if deliverable.review_for(user)
          haml_tag :img, :src => "/icons/exclamation.png", :alt => "You submitted too late."
          haml_tag :span, "#{deliverable.review_for(user).percentage}%" 
        else
          haml_tag :img, :src => "/icons/failed-closed.png", :alt => "You did not submit a version yet."
        end
      end
    elsif user.staff? then
      if deliverable.invisible? then
        haml_tag :img, :src => "/icons/document_invisible.png", :alt => "This deliverable is invisible to EITs"
      elsif deliverable.current? and not deliverable.ended? then
        haml_tag :img, :src => "/icons/document_to_solve.png", :alt => "EITs should be working on this document" if deliverable.eits_submitted.size<deliverable.eits.size
        haml_tag :img, :src => "/icons/submitted.png", :alt => "EITs should be working on this document" if deliverable.eits_submitted.size==deliverable.eits.size
      elsif deliverable.ended? and not deliverable.newest_submissions_all_graded? then
        haml_tag :img, :src => "/icons/exclamation.png", :alt => "This deliverable has submissions that have not been graded yet"
      elsif deliverable.ended? and deliverable.newest_submissions_all_graded? then
        haml_tag :img, :src => "/icons/done.png", :alt => "This deliverable is invisible to EITs"
      end
    end
  end

end

app/views/deliverables/_summary.html.haml
%div{:class => (deliverable.current? ? "current_deliverable" : "past_deliverable")}
	.summary
		%span.title
			= deliverable.title
		%span.time_label
			= "(#{time_span_to_due_date_in_words(deliverable)})" if deliverable.end_date
		%span.status_icon
			- status_icon(deliverable, current_user)
	.body
		%ul
			%li
				- if current_user.eit? then
					- if deliverable.submitted?(current_user) then
						= "You submitted #{deliverable.submissions_for(current_user).size} version(s). The latest one on #{deliverable.latest_submission(current_user).created_at}" 
					- else
						= "You did not submit a version yet."
				- elsif current_user.staff? then
					= "#{deliverable.eits_submitted.size}/#{deliverable.eits.size} Eits submitted so far."
			%li= "The deadline #{deliverable.current? ? "is" : "was"} on #{deliverable.end_date}"			
			%li= "This deliverable was last changed on #{deliverable.updated_at} by #{deliverable.author.name}"
		%p
			- if current_user.staff? then
				- if deliverable.versions.keys.max >= 1 then
					%p
						= link_to "Download all Submissions (Version #{deliverable.versions.keys.max})", download_project_deliverable_path(deliverable.project, deliverable)
						= current_user.latest_version_downloaded(deliverable) ? "Downloaded" : "Never downloaded"
				- if deliverable.ended? then 
					= link_to "Enter Grades", project_deliverable_reviews_path(deliverable.project, deliverable)
					- if deliverable.newest_submissions_all_graded? and deliverable.eits_submitted.size > 0 then
						= link_to "Upload Corrections", upload_project_deliverable_path(deliverable.project, deliverable)
					- else
						Please enter all grades first, then upload files.
			- elsif current_user.eit?
				= link_to "Add Submission", new_project_deliverable_submission_path(deliverable.project, deliverable)
				= link_to "Download correction", download_project_deliverable_path(deliverable.project, deliverable) if rev = deliverable.review_for(current_user) and rev.archive?

app/views/deliverables/new.html.haml
= render :partial => "projects/detail"
.new_deliverable_form
	= form_for @deliverable, :url => project_deliverables_url(@project) do |f|
		= render :partial => 'shared/error_messages', :locals => {:target => @deliverable}
		%legend Create a new Deliverable
		%ol
			%li
				= f.label :title
				= f.text_field :title
			%li
				= f.label :description
				= f.text_field :description
			%li
				= f.label :start, "Start date"
				= datetime_select :deliverable, :start_date, :start_year => Time.now.year - 1
			%li
				= f.label :end, "End date"
				= datetime_select :deliverable, :end_date, :start_year => Time.now.year - 1
			%li
				#button
					= submit_tag "cancel"
					= submit_tag "create"

app/views/deliverables/process_upload.html.haml
%h1= "Process Upload for \"#{@deliverable.title}\""

app/views/deliverables/upload.html.haml
%h1= "Upload corrected versions for \"#{@deliverable.title}\""
%p
  - if @deliverable.latest_version_nr == 0 then
    = "There was no submission yet, the upload is disabled."
  - else
    - if (cv = current_user.latest_downloaded_version_nr(@deliverable)) < @deliverable.latest_version_nr  then
      - if cv > 0
        = "The latest version you downloaded is #{cv}, however the current version is #{@deliverable.latest_version_nr}"  
      - else
        = "You never downloaded the submissions, the current version is #{@deliverable.latest_version_nr}."  
      = link_to "Download latest version", download_project_deliverable_path(@deliverable.project, @deliverable)
    = form_tag process_upload_project_deliverable_path,  :multipart => true do |f|
      %ol
        %li= label_tag :archive, "File"
        %li= file_field_tag :archive
        %li
          #button= submit_tag "Upload Corrections"