config/routes.rb
MestOMatic::Application.routes.draw do
  root :to => "welcome#index"
  
  resource :sessions
  resources :users do
    collection do
      get 'unassigned_roles'
      put 'assign_roles'
    end
  end
  resources :projects do
    resources :deliverables do
      member do
        get 'download'
        get 'upload'
        post 'process_upload'
      end
      resources :reviews do
        collection do
          post 'mass_create'
        end
      end
      resources :submissions
    end
    resources :teams
  end
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  match '/testlogin/:id' => 'sessions#testlogin'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110518183857
#
# Table name: users
#
#  id             :integer         not null, primary key
#  first_name     :string(255)
#  middle_names   :string(255)
#  last_name      :string(255)
#  identifier_url :string(255)
#  email          :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  type           :string(255)
#  class_of_id    :integer
#

class User < ActiveRecord::Base
  include ActiveModel::Validations
  SUBTYPES = %w[Eit Staff] 
  
  has_many :solutions
  belongs_to :class_of
  
  def self.attributes_protected_by_default # default is ["id","type"] 
    ["id"] 
  end
  
  validates :identifier_url, :presence => true, :uniqueness => true
  validates :email,          :presence => true, :uniqueness => true
  validates :first_name,     :presence => true, :on => :update
  validates :last_name,      :presence => true, :on => :update 
  validates :first_name,   :allow_nil => true, :capitalized => true
  validates :last_name,    :allow_nil => true, :capitalized => true
  validates :middle_names, :allow_nil => true, :capitalized => true
  validates :type,         :allow_nil => true, :inclusion => SUBTYPES
  validates_presence_of :class_of, :if => :eit?
  
  def identifier_name 
    email.split("@").first
  end

  def suggested_first_name
    first_name || email.split("@").first.split(".").first.capitalize
  end

  def suggested_last_name
    last_name || email.split("@").first.split(".").last.capitalize
  end
  
  def complete?
    !!self.valid?
  end
  
  def eit?
    type.eql?("Eit")
  end
  
  def staff?
    type.eql?("Staff")
  end
  
  def unassigned?
    type == nil
  end
  
  def name 
    "#{first_name} #{last_name}"
  end
  
  def User.types
    SUBTYPES
  end
  
  def User.all_unassigned
    User.all.select{|user| user.unassigned?}
  end
  
  def role=(role_name)
    if role_name and matchdata = role_name.match(/Eit \(Class of (\d{4})\)/) then
      self.type = "Eit"
      self.class_of = ClassOf.find_by_year(matchdata[1].to_i)
    else
      self.type = role_name
    end
  end
  
  def role
    if type.eql?("Eit") then
      "Eit (Class of #{class_of.year})"
    else
      type
    end
  end
  
  def User.all_roles
    ts = SUBTYPES.reject{|t| t.eql?("Eit")}
    ClassOf.all.each do |c|
      ts << "Eit (Class of #{c.year})"
    end
    return ts.sort
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:edit, :update]
  before_filter :ensure_signed_in
  before_filter :ensure_same_user_as_signed_in_user_or_staff, :only => [:edit, :update]
  before_filter :require_staff, :only => [:assign_roles, :unassigned_roles]
  
  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      redirect = session[:redirect_to]
      session[:redirect_to] = nil if redirect
      flash[:notice] = "Account has been updated"
      redirect_to(redirect || root_path)
    else
      render :action => "edit"
    end
  end

  def unassigned_roles
    @users = User.all_unassigned
    # @users = User.all
  end

  def assign_roles
    @users = User.update(params[:users].keys, params[:users].values).reject{|u| u.errors.empty?}
    if @users.empty?
      flash[:notice] = "Roles assigned"
      redirect_to unassigned_roles_users_path
    else
      render :action => "unassigned_roles"
    end
  end

  private
    def find_user
      @user = User.find(params[:id])
    end
    
    def ensure_same_user_as_signed_in_user_or_staff
      unless @user.eql?(current_user) or (current_user.staff? and not @user.staff?) then
        flash[:error] = "Not enough privileges to edit this user. Here is your profile"
        redirect_to(edit_user_path(current_user))
      end
    end
    
    def require_staff
      unless current_user.staff? then
        flash[:error] = "Not enough privileges"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_panel.html.haml
.user_panel
	- if signed_in?
		.text
		=current_user.name
		= "is #{current_user.type}" unless current_user.unassigned?
		#logout
			%a{:href => "/logout"}
				logout
		#clear
	- elsif(request.path_info=='/login')
		Not logged in
	- else
		%a{:href => "/login"}
			login

app/views/users/edit.html.haml
%h1 Please provide more information
= form_for @user, :as => :user, :url => user_path(@user) do |f|
	= render :partial => 'shared/error_messages', :locals => {:target => @user}
	%legend Edit your account
	%ol
		%li
			= f.label :first_name, "First Name"
			= f.text_field :first_name, :value => @user.suggested_first_name
		%li
			= f.label :middle_names, "Middle Names"
			= f.text_field :middle_names
		%li
			= f.label :last_name, "Last Name"
			= f.text_field :last_name, :value => @user.suggested_last_name
		%li
			%label Email
			= @user.email
		%li
			#button= submit_tag "save"

app/views/users/unassigned_roles.html.haml
%h1 Unassigned Roles
- if @users and not @users.empty?
	= form_tag  assign_roles_users_path, :method => :put do
		%table
			%tr
				%th Email
				%th Type
			- @users.each do |user|
				= fields_for "users[]", user do |f|
					%tr
						%td= user.email
						%td= f.select(:role, User.all_roles, :include_blank => true)
					
		#button= submit_tag "Assign"
- else
	No unassigned users at this time.
	= link_to "back", root_path