config/routes.rb
MestOMatic::Application.routes.draw do
  root :to => "welcome#index"
  
  resource :sessions
  resources :users do
    collection do
      get 'unassigned_roles'
      put 'assign_roles'
    end
  end
  resources :projects do
    resources :deliverables do
      member do
        get 'download'
        get 'upload'
        post 'process_upload'
      end
      resources :reviews do
        collection do
          post 'mass_create'
        end
      end
      resources :submissions
    end
    resources :teams
  end
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  match '/testlogin/:id' => 'sessions#testlogin'

end

app/models/project.rb
# == Schema Information
# Schema version: 20110518121401
#
# Table name: projects
#
#  id          :integer         not null, primary key
#  start       :date
#  end         :date
#  title       :string(255)
#  description :text
#  semester_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#  subject_id  :integer
#  type        :string(255)
#

class Project < ActiveRecord::Base
  SUBTYPES = %w[Assignment Quiz TeamProject]
  has_many :deliverables

  belongs_to :semester
  belongs_to :subject
  
  has_one  :class_of, :through => :semester  

  validates :title, :presence => true
  validates :start, :presence => true
  validates :semester, :presence => true
  validates :type, :presence => true, :inclusion => SUBTYPES
  
  def Project.types
    SUBTYPES
  end
  def eits
    semester.class_of.eits
  end
  def safe_title
    title.gsub(/\s/, "_").camelize.gsub(/[^a-zA-Z0-9]/, "")
  end
 
  def Project.for_user(user)
    if user.eit? then
      @projects = Project.by_class(user.class_of)
    elsif user.staff? then
      @projects = Project.all 
    else
      @projects = []
    end
  end
  private
    def Project.by_class(class_of)
      Project.all.select{|p| p.semester.class_of==class_of}
    end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :require_staff_or_eit
  before_filter :require_staff, :only => [:new, :create]
  before_filter :load_project, :only => [:show]
  before_filter :ensure_project_visible_to_eit, :only => [:show]
  
  def index
    @projects = Project.for_user(current_user)
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    @project.type = params[:project][:type] if params[:project] and params[:project][:type] #TODO: why do I need to set this?
    if @project.save
      redirect_to project_path(@project), :notice => "Successfully created the project #{@project.title}"
    else
      render :action => "new"
    end
  end
  
  def show
  end
  
  private
    def load_project
      @project =  Project.find(params[:id])
    end
    def ensure_project_visible_to_eit
      if current_user.eit? and current_user.class_of != @project.class_of then
        redirect_to projects_path
        flash[:error] = "This project is not available for you, here is a list of projects that are."
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def uncamel(str)
    return "" if str.nil?
    str = str.gsub(/([A-Z]+|[A-Z][a-z])/) {|x| ' ' + x }
    str = str.gsub(/[A-Z][a-z]+/) {|x| ' ' + x }
    return str.split(" ").reject{|part| part.empty?}.collect{|part| part.capitalize}.join(" ")
  end
end

app/views/projects/_detail.html.haml
%h1= "#{uncamel(@project.type)} \"#{@project.title}\""
.semester= "Class of #{@project.semester.class_of.year}" if @project.semester
.description= @project.description
.subject= "Subject: #{@project.subject.title}" if @project.subject
.start_date= "Start date: #{@project.start}"
.end_date= "End date: #{@project.end}" if @project.end
.timestamps
	= "Created: #{@project.created_at}"
	= "Updated: #{@project.updated_at}" unless @project.created_at == @project.updated_at
- if @project.is_a? TeamProject then
	%h2 
		- if current_user.staff? then
			= "Teams (#{@project.teams.size})"
		- else
			My Team
		= link_to "+", new_project_team_path(@project) if current_user.staff? and not @project.has_empty_teams? and not @project.unassigned_eits.empty?
	- unless @project.teams_for(current_user).empty? then
		%ol
			= render :partial => "teams/summary", :collection => @project.teams_for(current_user), :as => :team
	- else
		Not assigned to a team yet.
%h2
	= "Deliverables (#{@project.deliverables.select{|d| d.visible?(current_user)}.count})"
	= link_to "+", new_project_deliverable_path(@project) if current_user.staff?
= render :partial => "deliverables/summary", :collection => @project.deliverables.sort{|a,b| a.end_date <=> b.end_date}.select{|d| d.visible?(current_user)}, :as => :deliverable

app/views/projects/index.html.haml
%h1
	= "Projects (#{@projects.size})" 
	= link_to "+", new_project_path if current_user.staff?
%ul
	- @projects.each do |project|
		%li= link_to project.title, project_path(project) #Needed for STI

app/views/projects/new.html.haml
%h1 New Project
= form_for @project, :url => {:action => "create"} do |f|
	= render :partial => 'shared/error_messages', :locals => {:target => @project}
	%legend Create a new Project
	%ol
		%li
			%label Type
			- Project.types.each do |t|
				= f.label "type_#{t.downcase}", t
				= f.radio_button :type, t
		%li
			= f.label :title
			= f.text_field :title
		%li
			= f.label :description
			= f.text_field :description
		%li
			= f.label :subject
			= collection_select(:project, :subject_id, Subject.all, :id, :title, :include_blank => true)
		%li
			= f.label :semester
			= collection_select(:project, :semester_id, Semester.all, :id, :title)
		%li
			= f.label :start, "Start date"
			= date_select :project, :start, :start_year => Time.now.year - 1
		%li
			= f.label :end, "End date"
			= date_select :project, :end, :include_blank => true, :start_year => Time.now.year - 1
		%li
			#button= submit_tag "create"
		

app/views/projects/show.html.haml
= render :partial => "detail"