config/routes.rb
MestOMatic::Application.routes.draw do
  root :to => "welcome#index"
  
  resource :sessions
  resources :users do
    collection do
      get 'unassigned_roles'
      put 'assign_roles'
    end
  end
  resources :projects do
    resources :deliverables do
      member do
        get 'download'
        get 'upload'
        post 'process_upload'
      end
      resources :reviews do
        collection do
          post 'mass_create'
        end
      end
      resources :submissions
    end
    resources :teams
  end
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  match '/testlogin/:id' => 'sessions#testlogin'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :require_staff

  def index
    @deliverable = Deliverable.find(params[:deliverable_id])
    @submissions = @deliverable.latest_version
    @submissions.each do |sub|
      sub.review ||= Review.new
    end
  end
  
  def mass_create
    @deliverable = Deliverable.find(params[:deliverable_id])
    keys = params[:submissions].keys
    values = params[:submissions].values
    params[:submissions].each_pair do |k,v|
      v["review_attributes"]["reviewer_id"] ||= current_user.id.to_s
      review = Review.where(:submission_id => k).first #TODO: Could probably be done better (in form)
      v["review_attributes"]["id"] ||= review.id if review and review.id
    end
    Submission.update(params[:submissions].keys, values)
    redirect_to project_deliverable_reviews_path(@deliverable.project, @deliverable)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/index.html.haml
%h1= "#{@deliverable.project.title} - #{@deliverable.title}" 
%h2 Grading Sheet
%h3= "This deliverable was created by #{@deliverable.author.name}. Are you sure you want to grade it?" unless current_user.eql?(@deliverable.author) 
= form_tag mass_create_project_deliverable_reviews_path(@deliverable.project, @deliverable) do 
  %table{:border => 1} 
    %tr
      %th Name
      %th Revision
      %th Grade
      %th Remarks

    - @submissions.each do |submission|
      %tr
        = fields_for "submissions[#{submission.id}][review_attributes]", submission.review do |rev_f|
          %td= rev_f.label :user, submission.user
          %td= rev_f.label :version, submission.version
          %td= rev_f.text_field :percentage
          %td= rev_f.text_area :remarks
  %p
    - if (cv = current_user.latest_downloaded_version_nr(@deliverable)) < @deliverable.latest_version_nr and @deliverable.latest_version_nr > 0 then
      - if cv > 0
        = "The latest version you downloaded is #{cv}, however the current version is #{@deliverable.latest_version_nr}"  
      - else
        = "You never downloaded the submissions, the current version is #{@deliverable.latest_version_nr}."  
      = link_to "Download latest version", download_project_deliverable_path(@deliverable.project, @deliverable)
  #button= submit_tag "Save"